{
  "formatVersion": "1.1",
  "component": {
    "group": "com.braze",
    "module": "braze-segment-kotlin",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "braze-segment-kotlin-1.2.0.aar",
          "url": "braze-segment-kotlin-1.2.0.aar",
          "size": 18475,
          "sha512": "e0b5a906c8cea5e2869aae40ba18c798a3cfcbfab42e44bb651def45db7a4ab383ee3d49570a672a8a0e8b5878c308a29006d2619b7e10e0f4dd449bfd1bcfda",
          "sha256": "f678dee688bcf56971ec22cbee253d399634d8f9a0580c314b3e0050f85fb3e5",
          "sha1": "c84a98a0a8d0450681ea1106ddad9d1cae547ccb",
          "md5": "d64d8daf659d3aef453376e99355f310"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.appboy",
          "module": "android-sdk-ui",
          "version": {
            "requires": "23.2.1"
          }
        },
        {
          "group": "com.segment.analytics.kotlin",
          "module": "android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "braze-segment-kotlin-1.2.0.aar",
          "url": "braze-segment-kotlin-1.2.0.aar",
          "size": 18475,
          "sha512": "e0b5a906c8cea5e2869aae40ba18c798a3cfcbfab42e44bb651def45db7a4ab383ee3d49570a672a8a0e8b5878c308a29006d2619b7e10e0f4dd449bfd1bcfda",
          "sha256": "f678dee688bcf56971ec22cbee253d399634d8f9a0580c314b3e0050f85fb3e5",
          "sha1": "c84a98a0a8d0450681ea1106ddad9d1cae547ccb",
          "md5": "d64d8daf659d3aef453376e99355f310"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "braze-segment-kotlin-1.2.0-sources.jar",
          "url": "braze-segment-kotlin-1.2.0-sources.jar",
          "size": 5034,
          "sha512": "5a769912091ce592fa9599547c50f4031cd0621a7a59b627193cd8a536303076deabb54d13417568cc05911a5c80bf8490548c608b1d3edb2c796a6977f94e2c",
          "sha256": "d872f10bb5bb483c80d85efa250cd6f9e26e752c479e7fe0e707555e245e16f8",
          "sha1": "ab926c385e8fca363681ac4dde4cd02c648d5049",
          "md5": "ae6d9936d57ab5840d48ad1b548dec6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "braze-segment-kotlin-1.2.0-javadoc.jar",
          "url": "braze-segment-kotlin-1.2.0-javadoc.jar",
          "size": 290366,
          "sha512": "3f852d538bce13cc1009d86b18c3670819a1c4daff9428fb5fa36ace8baebc8ed41f71e144c71f2a957d055977716a309fb5d9699a8246f01a7a03735d47c3d8",
          "sha256": "d57833e88d94e133c5827284cae87aadd625773fa7a66ef0f5b3ffd423011f8f",
          "sha1": "fac41b1753028411a34adfd1a836d5973238bcad",
          "md5": "a82d5ddd321c69406efb1c171748aec3"
        }
      ]
    }
  ]
}
